version: '3.9'

services:
  ollama:
    image: ollama/ollama:0.5.7
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - evaluator-optimizer-workflow

  evaluator-optimizer-workflow:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: evaluator-optimizer-workflow
    ports:
      - 8080:8080
    depends_on:
      - ollama
    environment:
      spring.ai.ollama.base-url: http://ollama:11434
    networks:
      - evaluator-optimizer-workflow

networks:
  evaluator-optimizer-workflow: